### ISSUE TITLE
PHP Version defaults to 5.6

### ISSUE THREAD

**Issue by WeirdDNA** [pantheon-systems/localdev-issues#101]
I've created a brand new Drupal 8 sandbox site on Pantheon. (Feb 10).
Initialized that site with default Drupal configuration.  
Updated Localdev to the latest stable release: 1.0.1
Pulled that new site down via Localdev's init procedure.
While the site runs on PHP 7+ on Pantheon's servers, localdev/lando defaults to php 5.6 for this new site.  (Other projects are fine on 7)

After encountering this error, I've updated the .lando.yml file and the pantheon.yml file to include php: 7.4 and php_version: 7.4 respectively, stopping and starting the server does not pick up the change, and it's still attempting to serve via 5.6 within Localdev/Pantheon.

**Comment by WeirdDNA** [comment]
Fixed via forced rebuild, but... come on.

**Comment by interactiveRob** [comment]
I second this. Still an issue, the default should not be PHP 5.6.  Any sites with PHP 7+ features throw fatals and need a rebuild.

**Comment by interactiveRob** [comment]
@pantheon-jira Please re-open this issue and provide a fix.
